easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\News
        - App\Entity\Company
        - App\Entity\Zone
        - App\Entity\Owner
        - App\Entity\User
        - App\Entity\Reason
