<?php

namespace App\Form\Collection;

use App\Entity\News;
use App\Entity\Owner;
use App\Entity\User;
use App\Entity\Zone;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsOwnerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('price', MoneyType::class, [
                'label' => 'Precio'
            ])
            ->add('comment', TextareaType::class, [
                'label' => 'Comentario'
            ])
            ->add('zone', EntityType::class, [
                'label' => 'Zona',
                'class' => Zone::class,
                'placeholder' => 'Selecciona zona',
                'required' => false
            ])
            ->add('commercial', EntityType::class, [
                'label' => 'Comercial',
                'class' => User::class,
                'placeholder' => 'Selecciona un comercial',
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }

    public function getBlockPrefix()
    {
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return 'appbundle_news_owner';
    }
}
