<?php

namespace App\Form\Collection;

use App\Entity\Street;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StreetZoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
//            ->add('zone', EntityType::class, [
//                'class' => Zone::class,
//                'choice_label' => 'name',
//                'placeholder' => 'Selecciona una zona'
//            ])
            ->add('name', TextType::class, [
                'label' => 'Nombre Calle',
                'attr' => [
                    'placeholder' => 'Ejemplo: Alameda Urquijo'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Street::class,
        ]);
    }

    public function getBlockPrefix()
    {
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return 'appbundle_street';
    }
}
