<?php

namespace App\Form;

use App\Entity\News;
use App\Entity\Situation;
use App\Entity\User;
use App\Form\EventListener\AddStreetFieldListener;
use App\Form\EventListener\AddZoneFieldListener;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('commercial', EntityType::class, [
                'label' => 'Comercial',
                'class' => User::class,
                'placeholder' => 'Selecciona un comercial',
                'required' => false
            ])
            ->addEventSubscriber(new AddZoneFieldListener())
            ->addEventSubscriber(new AddStreetFieldListener())
            ->add('situation', EntityType::class, [
                'label' => 'Situación',
                'class' => Situation::class,
                'placeholder' => 'Selecciona una situación'
            ])
/*            ->add('reason', EntityType::class, [
                'label' => ' ',
                'class' => Reason::class,
                'placeholder' => 'Selecciona un motivo'
            ])*/
            ->add('portal', TextType::class, [
                'label' => 'Portal',
                'attr' => [
                    'placeholder' => 'Nº Portal',
                ]
            ])
            ->add('floor', TextType::class, [
                'label' => 'Piso',
                'attr' => [
                    'placeholder' => 'Piso',
                ]
            ])
            ->add('firstName', TextType::class, [
                'label' => 'Nombres',
                'attr' => [
                    'placeholder' => 'Nombres',
                ]
            ])
            ->add('lastName', TextType::class, [
                'label' => 'Apellidos',
                'attr' => [
                    'placeholder' => 'Apellidos',
                ]
            ])
            ->add('mobile', TextType::class, [
                'label' => 'Móvil',
                'attr' => [
                    'placeholder' => 'Móvil',
                ]
            ])
            ->add('phone', TextType::class, [
                'label' => 'Teléfono',
                'attr' => [
                    'placeholder' => 'Teléfono',
                ]
            ])
            ->add('email', TextType::class, [
                'label' => 'Correo',
                'attr' => [
                    'placeholder' => 'Correo',
                ]
            ])
            ->add('price', MoneyType::class, [
                'label' => 'Precio',
                'attr' => [
                    'placeholder' => 'Precio'
                ]
            ])
            ->add('comment', TextareaType::class, [
                'label' => 'Comentario',
                'attr' => [
                    'placeholder' => 'Comentario',
                    'cols' => 100,
                    'rows' => 5
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }

    public function getParent()
    {
        return parent::getParent(); // TODO: Change the autogenerated stub
    }

    public function getBlockPrefix()
    {
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return 'appbundle_news';
    }
}
