<?php

namespace App\Form;

use App\Entity\News;
use App\Entity\Owner;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OwnerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name', TextType::class, [
                'label' => 'Nombres'
            ])
            ->add('last_name', TextType::class, [
                'label' => 'Apellidos'
            ])
            ->add('email', EmailType::class, [
                'label' => 'Correo'
            ])
            ->add('phone', TelType::class, [
                'label' => 'Teléfono'
            ])
            ->add('mobile', TelType::class, [
                'label' => 'Móvil'
            ])
            ->add('news', CollectionType::class, [
                'label' => 'Noticias',
                'entry_type' => NewsType::class,
                'entry_options' => [
                    'label' => false
                ],
                'by_reference' => true,
                'allow_add' => true,
                'allow_delete' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Owner::class,
        ]);
    }

    public function getBlockPrefix()
    {
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return 'appbundle_owner';
    }

}
